In [1]:
import numpy as np
import pandas as pd
import os
import sys
import scipy
from scipy.linalg import logm
import math
import time
import matplotlib.pyplot as plt
from sklearn import datasets
import pickle
import sklearn.svm
from sklearn.linear_model import LogisticRegression
%matplotlib inline

In [2]:
os.chdir("C:\\Users\\PC\\Desktop\\Ensemble")

In [3]:
data = pd.read_csv("hgsc.csv")

In [4]:
data['class'] = data['class'].astype('category')

In [5]:
data['class'] = data['class'].cat.codes

In [6]:
data.head()

,class,ABAT,ABHD2,ACTB,ACTR2,ACTR5,ACVR2A,ADAMDEC1,ADCYAP1R1,AEBP1,...,WT1,XPO7,XPOT,YTHDC2,ZDHHC14,ZDHHC7,ZEB1,ZFP36,ZHX3,ZNF423
0,3,-0.010674,0.263376,-0.115492,-0.323565,0.005161,-0.504271,-1.283720,-0.433908,0.673072,...,0.077048,0.459961,-0.072049,0.243935,-0.056318,-0.204971,0.179639,-0.292136,-0.034261,0.490152
1,2,-0.710741,0.110421,0.532555,-0.253877,-0.389024,-0.121941,-1.732920,-0.727880,1.706110,...,0.547120,-0.674773,-0.236746,0.551354,0.215982,0.196677,1.467320,2.461040,0.415041,2.116880
2,0,0.881506,0.372862,0.052344,0.028721,-0.848119,-1.281180,1.524370,-0.288317,-2.010830,...,1.058170,0.350895,-0.000051,0.010498,0.592285,-0.338954,-0.842242,0.096242,-0.471005,-1.662190
3,2,-1.085090,0.415651,0.395376,-0.271050,0.146536,-0.363270,0.993823,-0.450427,1.999170,...,-0.677226,-0.109778,0.033163,0.760080,-1.169030,0.325604,1.785760,-0.212328,0.537493,-0.102138
4,2,-0.932230,0.045352,0.595068,0.187856,-0.200287,0.211144,1.844640,-0.416482,1.327800,...,0.961688,-0.009010,0.529045,-0.551470,-0.188697,0.157393,0.469166,1.748000,0.144196,-0.561641

In [7]:
X = data.drop(["class"],axis=1)
Y = data["class"]

In [ ]:
#Description of begging function from sklearn manual
#A Bagging classifier is an ensemble meta-estimator that fits base classifiers each on random subsets of the original dataset and then aggregate their individual predictions (either by voting or by averaging) to form a final prediction.

In [112]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
f = QuadraticDiscriminantAnalysis()

from sklearn.ensemble import BaggingClassifier
bagger = BaggingClassifier(base_estimator=f,n_estimators=100,max_samples=100)
bagger.fit(X,Y)
QDApreds = bagger.predict(X)

sum(QDApreds==Y)/len(Y)

0.96728016359918201

In [113]:

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
f = LinearDiscriminantAnalysis()

from sklearn.ensemble import BaggingClassifier
bagger = BaggingClassifier(base_estimator=f,n_estimators=100,max_samples=100)
bagger.fit(X,Y)
LDApreds = bagger.predict(X)

sum(LDApreds==Y)/len(Y)

0.94274028629856854

In [114]:
from sklearn import svm
f= svm.SVC()

from sklearn.ensemble import BaggingClassifier
bagger = BaggingClassifier(base_estimator=f,n_estimators=100,max_samples=100)
bagger.fit(X,Y)
SVMpreds = bagger.predict(X)

sum(SVMpreds==Y)/len(Y)

0.89570552147239269

In [115]:
from sklearn.ensemble import RandomForestClassifier
f = RandomForestClassifier()

from sklearn.ensemble import BaggingClassifier
bagger = BaggingClassifier(base_estimator=f,n_estimators=100,max_samples=100)
bagger.fit(X,Y)
Forestpreds = bagger.predict(X)

sum(Forestpreds==Y)/len(Y)

0.9468302658486708

In [116]:
frames = [LDApreds,QDApreds,SVMpreds,Forestpreds]
result = pd.DataFrame(frames)
result=result.transpose()

In [117]:
result.columns = ['LDA','QDA','SVM','Random Forest']

In [118]:
result

     LDA  QDA  SVM  Random Forest
0      3    3    3              3
1      2    2    2              2
2      0    0    0              0
3      2    2    2              2
4      2    2    2              2
5      3    3    3              3
6      0    0    0              0
7      2    2    2              2
8      1    1    1              1
9      3    3    3              3
10     1    1    1              1
11     0    0    0              0
12     3    3    3              3
13     0    0    0              0
14     1    1    1              1
15     0    0    0              0
16     0    0    0              0
17     3    3    3              3
18     1    1    1              1
19     0    0    0              0
20     3    3    3              3
21     0    0    0              0
22     3    3    3              3
23     0    3    0              0
24     2    2    2              2
25     0    0    0              0
26     3    3    3              3
27     0    0    0              0
28     3    3    3              3
29     0    0    0              0
..   ...  ...  ...            ...
459    0    0    0              0
460    1    1    1              1
461    1    1    1              1
462    1    1    1              1
463    1    1    1              1
464    1    3    1              1
465    0    0    0              0
466    2    2    2              2
467    1    1    1              1
468    2    2    2              2
469    1    1    1              1
470    1    1    2              2
471    2    2    2              2
472    0    2    0              0
473    2    2    2              2
474    1    1    1              1
475    0    0    0              0
476    3    3    3              3
477    0    0    0              0
478    1    1    1              1
479    2    2    2              2
480    0    0    0              0
481    3    3    3              3
482    2    2    2              2
483    2    2    3              2
484    1    1    1              1
485    0    0    0              0
486    0    0    0              0
487    3    3    3              3
488    2    2    2              2

[489 rows x 4 columns]

In [119]:
lr = LogisticRegression()

In [120]:
lr.fit(result,Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [121]:
logpred = lr.predict(result)

In [122]:
sum(logpred==Y)/len(Y)

0.76278118609406953